<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Ste si istí, že chcete túto položku zmazať?',
    'Create' => 'Vytvoriť',
    'Create Status' => 'Vytvoriť stav',
    'Create Time' => 'Čas vytvorenie ',
    'Created Date' => 'Dátum vytvorenia',
    'Data' => 'Data',
    'Delete' => 'Odstrániť',
    'ID' => 'ID',
    'Message' => 'Message',
    'Permissions' => 'Oprávnenie ',
    'Reset' => 'Reset',
    'Search' => 'Hľadať',
    'Statuses' => 'Stavy',
    'Title' => 'Názov',
    'Update' => 'Aktualizácia',
    'Update Time' => 'Čas Aktualizácia',
    'Update {modelClass}: ' => 'ModelClass} {aktualizácia: ',
    'Updated Date' => 'Aktualizovaný Date ',
    'Verification Code' => 'Overovací kód',
];